GET http://localhost:3000
Accept: application/json

###
POST http://localhost:3000/
Content-Type: application/json

{}

###
POST http://localhost:3000/
Content-Type: application/x-www-form-urlencoded

1 12 124
###
